### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by sultanassi95** [FACG5/Later-team#21]
# Hi,

:sob: 
Can you please have a look at the [CSS file](https://github.com/FACG5/Later-team/blob/master/puplic/css/style.css), it looks messy, doesn't it?

I think it will be cool if we have it re-factored to look like this:

``` CSS
* {
    margin: 0;
    padding: 0;
}

.some-class {
    width: 100px;
    height: 100px;
}

.another-class {
    background-color: #fff;
    font-size: 16px;
}

```

## Things to consider:
- Indentation.
- White lines between every block.
- Each property should be in a separated line.
